apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/managed-by: kargocd
  name: passion-mansour-teambeam-frontend
  namespace: default
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: passion-mansour-teambeam-frontend
                port:
                  number: 3000