apiVersion: v1
kind: Secret
metadata:
  name: envsecret
type: Opaque
data:
  NEXT_PUBLIC_BASE_URL: aHR0cDovLzM0LjIyLjEwOC4yNTA6ODA4MC9hcGk=
  NEXT_PUBLIC_TEST: YWJjZGVmZw==
  NEXT_PUBLIC_DECODING: 6rCA64KY64uk652866eI67CU7IKs